---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      name: web-app
  template:
    metadata:
      labels:
        name: web-app
    spec:
      containers:
      - name: application
        image: chinmayicr27/web-app:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    name: web-app
